sonar.projectKey=Centro-Medico-Pichardo
sonar.projectName=Centro Medico Pichardo
sonar.host.url=http://localhost:9000

# Esta línea es la más importante: indica que analice la carpeta actual
sonar.sources=.

# Excluye carpetas que no son código de tu autoría para no falsear el reporte
sonar.exclusions=**/node_modules/**, .next/**, out/**

sonar.sourceEncoding=UTF-8

# Prueba final Pipeline CI
# Prueba final Pipeline CI